// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "language": string;
      "novelFontSize": number;
      "bookStoragePath": string;
      "selectedNovelPath": string;
      "shortcutForward": string;
      "shortcutBackward": string;
      "shortcutBoss": string;
      "shortcutShow": string;
    };
  }
}
